version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5434:5432 #{port in host(myPC) : {port in Container}}
    #environment variables, like: db's username, password...
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dbtest
    networks:
      - nestjs-network
networks:
  nestjs-network:
#docker compose up -d
